# Generated by Django 3.1.2 on 2020-10-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Salary')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Post office',
                'verbose_name_plural': 'Post offices',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last name')),
                ('middleName', models.CharField(max_length=50, verbose_name='Middle name')),
                ('slug', models.SlugField(unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.position')),
                ('postOffice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.postoffice')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
