# Generated by Django 3.1.2 on 2020-10-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='position',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='postoffice',
            name='slug',
        ),
    ]
