# Generated by Django 3.1.2 on 2020-10-05 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201005_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last name')),
                ('middleName', models.CharField(max_length=50, verbose_name='Middle name')),
            ],
            options={
                'verbose_name': 'Follower',
                'verbose_name_plural': 'Followers',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Publishing House',
                'verbose_name_plural': 'Publishing Houses',
            },
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=datetime.date.today, verbose_name='Subscription started')),
                ('term', models.PositiveSmallIntegerField(default=1, verbose_name='Subscription term(month)')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.follower')),
                ('postOffice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.postoffice')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.publication')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Count')),
                ('postOffice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.postoffice')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.publication')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Region Index')),
                ('postOffice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.postoffice')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='publishingHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.publishinghouse'),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.region')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.AddField(
            model_name='follower',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.house'),
        ),
    ]
